name: sync_nix

permissions:
  contents: write

on:
  schedule:
    - cron: "10 3 * * *"
  workflow_dispatch:

jobs:
  lints:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Check flake inputs
        uses: DeterminateSystems/flake-checker-action@main
        with:
          flake-lock-path: ./nix/flake.lock
          ignore-missing-flake-lock: false
      - uses: cachix/cachix-action@v15
        with:
          name: "${{ vars.CACHIX_OWNER || github.repository_owner }}"
          skipPush: "${{ github.event_name == 'pull_request' }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Rebase
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git status
          git reset --hard

          git remote add upstream https://github.com/wez/wezterm.git
          git fetch upstream main
          git rebase upstream/main
      - name: Build default package
        run: nix build --no-link --no-update-lock-file -L ./nix
      - name: Push
        run: |
          git push --force-with-lease
